# Change these first
owner: LazerPay-Finance # Your GitHub organization or username, where this repository lives
repo: lazerpay-status # The name of this repository

sites:
  - name: Lazerpay Website
    url: https://www.lazerpay.finance
  - name: Lazerpay Dashboard
    url: https://dashboard.lazerpay.finance
  - name: Lazerpay API
    url: https://api.lazerpay.engineering/api/v1

assignees:
  - iamnotstatic
  - franko4don

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.lazerpay.finance
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Lazerpay** Unlock global payments for your business today"
  introMessage: Get paid in crypto from anywhere and withdraw instantly to your bank account, or invest your revenue to earn more. Create a free account now."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
